version: "3.8"
services:
  preload:
    container_name: database-preload
    build: ../database
    # Load all files from ../import in repo defined in ./graphdb-repo-config.ttl
    entrypoint: [
      "/opt/graphdb/dist/bin/importrdf",
      "preload", "--force", "--recursive", "-q", "/tmp", "-c",
      "/opt/graphdb/graphdb-repo-config.ttl",
      "/opt/graphdb/home/graphdb-import"
    ]
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    volumes:
      - ../database/graphdb-data:/opt/graphdb/home
      - ./import:/opt/graphdb/home/graphdb-import
      - ./graphdb-repo.ttl:/opt/graphdb/graphdb-repo-config.ttl
