version: "3.8"
services:
  database:
    container_name: database
    hostname: database
    build: ./database
    restart: unless-stopped
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - "7200:7200"
      - "7300:7300"
    volumes:
      - ./database/graphdb-data:/opt/graphdb/home

  refine:
    image: ontotext/refine
    restart: unless-stopped
    environment:
      SERVER_HOST: localhost
      GRAPHDB_ADDRESS: http://database:7200
      GRAPHDB_REPOSITORY: sgdb
    ports:
      - "7333:7333"
    volumes:
      - ./refine/refine-data:/opt/ontorefine/data

  backend:
    container_name: backend
    hostname: backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    hostname: frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules